buildVariable: true
category:
- SERIF
familyName: Noto Serif Gujarati
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifGujarati.glyphs
